Add ISSUE_TEMPLATE
codeigniter4/.github pull request #11
Opened 2023-09-07 20:41 UTC by kenjis

2023-09-09 11:13 UTC, MGatner requested changes
This is the first change that really seems to make the decision that this repo is a template for **the CodeIgniter Organization**, not for any devs working with CodeIgniter in their own spaces. I'm not opposed but want to be explicit about that choice.

2023-09-09 11:13 UTC, MGatner commented on .github/ISSUE_TEMPLATE/feature_request.md
> +Please submit feature requests to [Discussions](https://github.com/codeigniter4/shield/discussions/categories/ideas).
This should not be Shield-specific.

2023-09-09 12:02 UTC, kenjis commented on .github/ISSUE_TEMPLATE/feature_request.md
> +Please submit feature requests to [Discussions](https://github.com/codeigniter4/shield/discussions/categories/ideas).
Thanks! Fixed.

2023-09-10 11:17 UTC, MGatner commented
@kenjis do you see this repo as an internal tool for the CodeIgniter organization?

2023-09-10 20:44 UTC, kenjis commented
Yes! This repo is for the CodeIgniter organization.
Not for everyone who uses CI4.

2023-09-10 20:52 UTC, kenjis commented
@MGatner I sent #13

2023-09-11 00:23 UTC, MGatner approved these changes

2023-09-11 00:26 UTC, merged